title: Loji po polsku
email: jakub.lechocki@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog programistyczny, JavaScript, front-end, ciekawostki
baseurl: "/po-polsku" # the subpath of your site, e.g. /blog
url: "https://loji.github.io/po-polsku" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jlechocki
github_username:  loji
lang: pl

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
